tasks:
  build-deps:
    runner: razorci/openjdk
    runner: razorci/maven:3-alpine
    steps:
    - checkout
    - commands:
      - mvn dependency:go-offline # gets the project dependencies
      - mvn package
