tasks:
  build-deps:
    runner: razorci/openjdk
    steps:
    - checkout
    - cache/pull:
        key: maven-repo-{{ checksum "pom.xml" }}
        fallback_key: maven-repo-

    - run: mvn -q clean package
 
    - cache/push:
        key: maven-repo-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2 
